const fs = require("fs");
const path = require("path");

// Get network from command line argument
const network = process.argv[2];

if (!network) {
  console.error("Error: Network argument is required");
  console.error("Usage: node scripts/prepare.js <network>");
  console.error("Available networks: mainnet, sepolia");
  process.exit(1);
}

// Load networks configuration
const networksPath = path.join(__dirname, "..", "networks.json");
const networks = JSON.parse(fs.readFileSync(networksPath, "utf8"));

if (!networks[network]) {
  console.error(`Error: Network "${network}" not found in networks.json`);
  console.error(`Available networks: ${Object.keys(networks).join(", ")}`);
  process.exit(1);
}

const networkConfig = networks[network];

// Load template
const templatePath = path.join(__dirname, "..", "subgraph.template.yaml");
let template = fs.readFileSync(templatePath, "utf8");

// Replace network placeholders
template = template.replace(/{ { network } }/g, network);

// Replace SocietyProtocolBadges placeholders
template = template.replace(
  "{ { SocietyProtocolBadges.address } }",
  networkConfig.SocietyProtocolBadges.address,
);
template = template.replace(
  "{ { SocietyProtocolBadges.startBlock } }",
  networkConfig.SocietyProtocolBadges.startBlock,
);

// Replace EasyAuction placeholders
template = template.replace(
  "{ { EasyAuction.address } }",
  networkConfig.EasyAuction.address,
);
template = template.replace(
  "{ { EasyAuction.startBlock } }",
  networkConfig.EasyAuction.startBlock,
);

// Replace vipManager placeholders
template = template.replace(
  "{ { vipManager.address } }",
  networkConfig.vipManager.address,
);
template = template.replace(
  "{ { vipManager.startBlock } }",
  networkConfig.vipManager.startBlock,
);

// Handle optional CommunityRegistry block
if (networkConfig.CommunityRegistry) {
  // Remove the conditional markers and replace placeholders
  template = template.replace(/^\s*# \{\{#CommunityRegistry\}\}\n/m, "");
  template = template.replace(/^\s*# \{\{\/CommunityRegistry\}\}\n?/m, "");
  template = template.replace(
    "{ { CommunityRegistry.address } }",
    networkConfig.CommunityRegistry.address,
  );
  template = template.replace(
    "{ { CommunityRegistry.startBlock } }",
    networkConfig.CommunityRegistry.startBlock,
  );
} else {
  // Remove the entire CommunityRegistry block including its markers
  template = template.replace(
    /^\s*# \{\{#CommunityRegistry\}\}[\s\S]*?^\s*# \{\{\/CommunityRegistry\}\}\n?/m,
    "",
  );
}

// Write output
const outputPath = path.join(__dirname, "..", "subgraph.yaml");
fs.writeFileSync(outputPath, template);

// Generate auction-config.ts from AUCTION_ID env variable
// Set AUCTION_ID=<id> to index only that auction; leave unset (or "0") to index all
const rawAuctionId = process.env.AUCTION_ID;
let auctionId = "0";
if (rawAuctionId && /^\d+$/.test(rawAuctionId)) {
  // Normalize by stripping leading zeros, but preserve a single "0" for the all-auctions case
  auctionId = rawAuctionId.replace(/^0+(?=\d)/, "");
} else if (rawAuctionId && !/^\d+$/.test(rawAuctionId)) {
  console.warn(
    `Warning: Invalid AUCTION_ID "${rawAuctionId}" — expected a decimal number. Falling back to "0".`,
  );
}
const auctionConfigPath = path.join(
  __dirname,
  "..",
  "src",
  "auction-config.ts",
);
const auctionConfigContent = `// This file is auto-generated by scripts/prepare.js — do not edit manually.
// Set the AUCTION_ID environment variable to restrict indexing to a single auction.
// A value of "0" (the default) means all auctions are indexed.
export const AUCTION_ID_FILTER: string = "${auctionId}";
`;
fs.writeFileSync(auctionConfigPath, auctionConfigContent);

console.log(`✅ Generated subgraph.yaml for network: ${network}`);
console.log(
  `   - SocietyProtocolBadges: ${networkConfig.SocietyProtocolBadges.address}`,
);
console.log(`   - EasyAuction: ${networkConfig.EasyAuction.address}`);
console.log(`   - SocietyVipManager: ${networkConfig.vipManager.address}`);
console.log(
  `   - AUCTION_ID filter: ${auctionId === "0" ? "all auctions" : auctionId}`,
);
