// This file is auto-generated by scripts/prepare.js — do not edit manually.
// Set the AUCTION_ID environment variable to restrict indexing to a single auction.
// A value of "0" (the default) means all auctions are indexed.
export const AUCTION_ID_FILTER: string = "0";
